spring:
  datasource:
    url: jdbc:h2:mem:reviewdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.hibernate.SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info   # Expose only health & info (can add more if needed)
  endpoint:
    health:
      show-details: always      # Show full health details
